# syntax=docker/dockerfile:1.7-labs
FROM ros:humble

SHELL ["/bin/bash", "-c"]

ARG FOLDER_NAME=rc-brain
ARG WORKSPACE_DIR=/home/cev
WORKDIR $WORKSPACE_DIR

# Source the ROS2 environment automatically when a new shell is created
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> ~/.bashrc
RUN echo "source $WORKSPACE_DIR/install/setup.bash" >> ~/.bashrc

# Install dev tools
RUN apt-get update
RUN apt-get install -y curl
RUN curl -fsSL https://apt.llvm.org/llvm-snapshot.gpg.key | tee /etc/apt/trusted.gpg.d/apt.llvm.org.asc
RUN cat /etc/apt/trusted.gpg.d/apt.llvm.org.asc
RUN echo $'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy main\n' \
    $'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy main\n' \
    $'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main\n' \
    $'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-18 main\n' \
    $'deb http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main\n' \
    $'deb-src http://apt.llvm.org/jammy/ llvm-toolchain-jammy-19 main\n' \
    | tee -a /etc/apt/sources.list
RUN apt-get update
RUN apt-get install -y clang-format clang-format-19

# Init rosdep and update package index
# for some reason we need to do this
RUN rm /var/lib/dpkg/info/libc-bin.* 
RUN apt-get clean
RUN apt-get update
RUN apt-get install -y libc-bin
RUN rosdep update --rosdistro $ROS_DISTRO

RUN mkdir -p src/$FOLDER_NAME

# Copy install.sh
COPY --parents ./install.sh src/$FOLDER_NAME

# Run install.sh
RUN src/$FOLDER_NAME/install.sh

COPY --parents ./*/package.xml src/$FOLDER_NAME
RUN source /opt/ros/$ROS_DISTRO/setup.bash && rosdep install --from-paths src -r -y
