# General settings for the Kalman Filter node output
odometry_settings:
  publish_rate: 100 # Publish rate of the filter in Hz

  main_model: "ackermann" # Main model to use for the filter

  topic: "/odometry/filtered" # Topic to publish the odometry data
  base_link: "base_link" # Base link frame ID
  odom_frame: "odom" # Odometry frame ID

  publish_tf: false

# Define the sensors used by the node
sensors:
  witmotion_imu:
    type: "IMU" # Sensor type (IMU, GPS, etc.)
    topic: "/imu" # Topic to subscribe to
    frame_id: "imu_frame" # Frame ID for the sensor data
    
    state: ["yaw"] # State variables to use from the sensor data
    covariance_multiplier: 1.0 # Multiplier to multiply message covariance by
    use_message_covariance: true
    estimator_models: ["ackermann", "cartesian"] # List of strings representing models to use for the sensor data by name

  encoder_odometry:
    type: "RAW"
    topic: "/sensor_collect"
    frame_id: "odom_frame"

    state: ["d_x", "tau"]
    covariance_multiplier: 2.0
    estimator_models: ["ackermann", "cartesian"]

# Define update models with their parameters
update_models:
  ackermann:
    type: "ACKERMANN" # Model type (ACKERMANN, CARTESIAN, etc.)
    state: ["x", "y", "d_x", "d_y", "yaw", "tau"] # State variables to use from the model in updates
    estimator_models: []
  cartesian:
    type: "CARTESIAN"
    state: ["x", "y", "d_x", "d_y", "yaw", "d_yaw"] 
    estimator_models: ["ackermann"]
